apiVersion: v1
kind: Pod 
metadata:
  name: postgres-pod 
  labels: 
    app: postgres 
spec:  
  containers: 
    - name: postgres-container  
      image: ooido/pg-pod
      imagePullPolicy: Always
      ports: 
        - containerPort: 5432 
      envFrom:
        - configMapRef:
            name: postgres-config
      volumeMounts: 
        - mountPath: /var/lib/postgresql/data
          name: db-data
  volumes: 
    - name: db-data #I'm attaching the volume in the container, labelled as "db-data" to an external volume 
      persistentVolumeClaim:
        claimName: postgres-pvc #I'm storing it somewhere that will get destroyed, only good for temporary data.
                  # If the pod is destroyed, all the data is destroyed. 
                  # For you guys, you should be storing it in AWS EBS
      #    env:
      #      - name: POSTGRES_USER
      #        valueFrom:
      #          secretKeyRef:
      #            name: mysecret
      #            key: username
      #      - name: POSTGRES_PASSWORD
      #        valueFrom:
      #          secretKeyRef:
      #            name: mysecret
      #            key: password
      #      - name: POSTGRES_DB
      #        valueFrom:
      #          secretKeyRef:
      #            name: mysecret
      #            key: url
      #
      #
      #
      #
# Create a kustomization.yaml file with SecretGenerator
#  $ cat <<EOF >./kustomization.yaml
#secretGenerator:
#  - name: db-user-pass
#    literals:
#      - username=admin
#      - password=secret
#  EOF



