apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: banking-api-monitor
  namespace: ooido-space
  labels:
    app: banking-api
    prometheus: devops
spec:
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
  namespaceSelector:
    matchNames:
    - ooido-space
  selector:
    matchLabels:
      app: banking-api